run:
  timeout: 30m
  tests: true
  issues-exit-code: 1

output:
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - bodyclose
    - exhaustive
    #- exhaustruct
    #- goconst
    - gofmt
    - inamedparam
    #- musttag
    - nosprintfhostport
    - perfsprint
    - sloglint
    - unconvert
    #- unparam
    - wastedassign
    - whitespace
    - gosimple

linters-settings:
  gofmt:
    # Apply the rewrite rules to the source before reformatting.
    # https://pkg.go.dev/cmd/gofmt
    # Default: []
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
