header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CardinalHQ, Inc
    copyright-year: 2025

  paths-ignore:
    - go.sum
    - go.mod
    - 'bin'
    - .github
    - '**/testdata/**'
    - '**/*.md'
    - '**/*.yaml'
    - .licenserc.yaml
    - 'LICENSE'
    - 'NOTICE'
    - .gitignore
    - .dockerignore
    - .helmignore
    - .idea

  comment: on-failure

  language:
    rl:
      extensions:
        - '.rl'
      comment_style_id: DoubleSlash
    dot:
      extensions:
        - '.dot'
      comment_style_id: Hashtag

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - go.mod
